// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Dkax_kyFJ8sGjn3vjq8BAbILWgfgruI',
    appId: '1:928583296119:web:86acf12b48462197e25272',
    messagingSenderId: '928583296119',
    projectId: 'tp-flutter-firebase-3b10d',
    authDomain: 'tp-flutter-firebase-3b10d.firebaseapp.com',
    storageBucket: 'tp-flutter-firebase-3b10d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc09VstD0GPlKthvv330cAxB2iIU13v-s',
    appId: '1:928583296119:android:da7323abd5fde401e25272',
    messagingSenderId: '928583296119',
    projectId: 'tp-flutter-firebase-3b10d',
    storageBucket: 'tp-flutter-firebase-3b10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5QKTBN8qpI8drLbUsJWMHmpJceffr9qY',
    appId: '1:928583296119:ios:7379a6a669c2c90ce25272',
    messagingSenderId: '928583296119',
    projectId: 'tp-flutter-firebase-3b10d',
    storageBucket: 'tp-flutter-firebase-3b10d.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5QKTBN8qpI8drLbUsJWMHmpJceffr9qY',
    appId: '1:928583296119:ios:1a8a85b371883081e25272',
    messagingSenderId: '928583296119',
    projectId: 'tp-flutter-firebase-3b10d',
    storageBucket: 'tp-flutter-firebase-3b10d.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
